### Working with PyTorch Examples

In [2]:
import torch

In [3]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-34,  56,  83, -50,  80,   0])

In [4]:
# 2 X 3 matrices 0f zeros
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# 3 X 2 Matrix
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [6]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
input = torch.empty(2,3)
input

tensor([[6.4047e+30, 4.5310e-41, 2.7248e-27],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [8]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [9]:
linspace = torch.linspace(3, 10, 5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
logspace = torch.logspace(-10, 10, 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [11]:
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
a=torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[              0,       398589920,       372934032],
        [138869984861776,               0,               0]])

### Advanced Examples with Pytorch

In [13]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [14]:
%%time
start_time = time.time()    
print(f'start time is: {start_time}')

# matrix operations here
zeros = torch.zeros(1, 1)

end_time = time.time()
print(f'end time is {end_time}')

elapsed_time = end_time - start_time
print(f"elapse time is: {elapsed_time:.4f}")

start time is: 1757189864.9964457
end time is 1757189864.9967372
elapse time is: 0.0003
CPU times: user 279 μs, sys: 209 μs, total: 488 μs
Wall time: 403 μs


* Matrix Multipliaction of Tensors(tensor.matmul) and Numpy(np.dot)

In [15]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch_rand1.numpy()
np_rand2 = torch_rand2.numpy()

start_time = time.time()
rand = torch.matmul(torch_rand1, torch_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Torch time: {elapsed_time:.8f}")


start_time = time.time()

rand = np.dot(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Numpy Time:{elapsed_time:.8f}")

Torch time: 1.24154544


MemoryError: Unable to allocate 3.64 TiB for an array with shape (100, 100, 100, 100, 100, 100) and data type float32

* error above bcos of memory from large Numpy array with CPU. Adjusted code below to allow Numpy array with CPU

In [18]:
torch_rand1 = torch.rand(100, 100).to(device)
torch_rand2 = torch.rand(100, 100).to(device)
np_rand1 = torch_rand1.numpy()
np_rand2 = torch_rand2.numpy()

start_time = time.time()
rand = torch.matmul(torch_rand1, torch_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Torch time: {elapsed_time:.8f}")


start_time = time.time()

rand = np.dot(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Numpy Time: {elapsed_time:.8f}")

Torch time: 0.00597882
Numpy Time: 0.00051045


* embeddings, torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the examples of functions/methods with pytorch docs)

In [25]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 10 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 0, 1, 1, 1, 1, 1, 1, 1])


In [26]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [27]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [28]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [29]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [30]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [31]:
input = torch.zeros(2, 3, 4)
out1 = input.transpose(0, 1)
out2 = input.transpose(-2,-1)
print(out1.shape)
print(out2.shape)
# torch.permute works the same but you provide the new order of dimensions instead of the dimensions you'd like to swap.

torch.Size([3, 2, 4])
torch.Size([2, 4, 3])


In [34]:
out3 = input.transpose(2,1)
out3.shape

torch.Size([2, 4, 3])

In [35]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-9.4590,  0.6150,  8.3574], grad_fn=<SqueezeBackward4>)


In [37]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [38]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 0.2626, -0.3899, -0.0459,  0.5356, -0.3938, -0.6201],
        [ 0.0696, -1.0117, -1.6795,  0.1496, -0.3571, -0.8610],
        [-0.7876,  1.1544, -0.0303,  2.4276, -0.5580, -1.1789],
        [-0.2317, -0.9215, -1.0096,  0.6754, -0.4608, -1.2462]],
       grad_fn=<EmbeddingBackward0>)


In [39]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
# print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [40]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64
float_32 = torch.rand(2,3)
#type float32
# print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [41]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
# print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [47]:
torch.rand(2, 3, 5)

tensor([[[0.2743, 0.1345, 0.9569, 0.8548, 0.5219],
         [0.1153, 0.2327, 0.9624, 0.4295, 0.3357],
         [0.4491, 0.7800, 0.1060, 0.5975, 0.5147]],

        [[0.3507, 0.4298, 0.0159, 0.1915, 0.0505],
         [0.6837, 0.6514, 0.2010, 0.1514, 0.5422],
         [0.3481, 0.5383, 0.8319, 0.1856, 0.5809]]])

In [43]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
# print(input)
print(output[:, -1, :])

tensor([[0.0767, 0.3647, 0.2751, 0.7618, 0.2722, 0.4260, 0.1239, 0.4367, 0.4231,
         0.8657],
        [0.1572, 0.2108, 0.2206, 0.4179, 0.4902, 0.1085, 0.9080, 0.4709, 0.0756,
         0.4717],
        [0.6177, 0.5927, 0.1268, 0.3404, 0.8060, 0.4333, 0.9202, 0.1336, 0.8191,
         0.6377],
        [0.8564, 0.7705, 0.1383, 0.8080, 0.0246, 0.5969, 0.9769, 0.8599, 0.9796,
         0.8490],
        [0.4151, 0.6143, 0.7870, 0.9617, 0.7809, 0.2220, 0.9264, 0.6579, 0.6434,
         0.1488],
        [0.2194, 0.1274, 0.5841, 0.9039, 0.2814, 0.0172, 0.6306, 0.8392, 0.1693,
         0.2521],
        [0.8423, 0.5734, 0.1023, 0.1982, 0.1544, 0.9581, 0.3008, 0.4369, 0.2594,
         0.5480],
        [0.6100, 0.3380, 0.6081, 0.8880, 0.4269, 0.7367, 0.6936, 0.9762, 0.1033,
         0.9902],
        [0.1735, 0.9234, 0.1024, 0.8248, 0.6584, 0.4169, 0.9822, 0.0821, 0.6872,
         0.4668],
        [0.6476, 0.7140, 0.5092, 0.5594, 0.8243, 0.2177, 0.1538, 0.8134, 0.1443,
         0.8133],
        [0

IndexError: too many indices for tensor of dimension 2

* Activation Function (ReLU, Sigmoid, tanh)

In [52]:
x = torch.tensor([10], dtype=torch.float32)
y = F.sigmoid(x)
print(y)

tensor([1.0000])


In [48]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])
